### ISSUE TITLE
Buy a camera for the RPI

### ISSUE THREAD

**Issue by rodralez** [rodralez/rpi_fe#3]
There are two options for a camera for the RPI:

1. A Raspberry Pi MIPI CSI Camera. https://www.arducam.com/raspberry-pi-camera-pinout/
2. A USB camera.

**Comment by klarasrl** [comment]
Raspberry Pi MIPI CSI Camera
> a) [Camara para Rpi0 5mp](https://articulo.mercadolibre.com.ar/MLA-756227481-raspberry-pi-zero-modulo-camara-5mp-csi-camera-module-rpi0-_JM#position=11&search_layout=stack&type=item&tracking_id=ff017f27-9e65-4c49-830e-f7767e3d735b)
> b) [Camara "usada" para Rpi V2 8mp](https://articulo.mercadolibre.com.ar/MLA-1186499971-camara-para-raspberry-pi-v2-8-megapixels-cable-conector-_JM#position=7&search_layout=stack&type=item&tracking_id=cc43f4c6-0173-400e-9aa7-50d2d8b95675)

**Comment by rodralez** [comment]
The camera **Raspberry Pi Zero Modulo Camara 5mp Csi Camera Module Rpi0** was bought at Mercado Libre. It arrives on Friday October 21st.
